Update Box2D to version 2.4.1
codenamecpp/carnage3d pull request #67
Opened 2021-11-20 21:43 UTC by marmichalski

This should be fine, but would be great if someone could run the premake build. I am creating a cmake build env and that's where I have tested these changes. There is quite a few whitelines changes in touched files, I did not try to resolve them in any way, as unified line endings are my preference :P

2021-11-21 01:17 UTC, marmichalski commented on Makefile
> +	wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-linux.tar.gz && \
Updated premake also :shrug:

2021-11-21 01:17 UTC, marmichalski commented on Makefile
> -	.build/premake5 --file=third_party/Box2D/premake5.lua gmake
box has moved to cmake

2021-11-22 22:27 UTC, diath requested changes

2021-11-22 22:27 UTC, diath commented on src/PhysicsManager.cpp
> +    b2FixtureData_map fxdata = (b2FixtureData_map*) mapFixture->GetUserData().pointer;
```suggestion
    b2FixtureData_map fxdata = static_cast<b2FixtureData_map*>(mapFixture->GetUserData().pointer);
```

2021-11-22 22:27 UTC, diath commented on src/PhysicsManager.cpp
> +    b2FixtureData_map fxdata = (b2FixtureData_map*) mapFixture->GetUserData().pointer;
```suggestion
    b2FixtureData_map fxdata = static_cast<b2FixtureData_map*>(mapFixture->GetUserData().pointer);
```

2021-11-25 12:42 UTC, codenamecpp commented
Oh, I didn't expect that. Nice work, thanks, @marmichalski !

As for 'static_cast' over 'c-style' cast, I haven't decided yet what I prefer more, usually I'm too lazy to write ***_cast<> etc but in general, I don't mind.

2021-11-25 23:06 UTC, marmichalski commented
> Oh, I didn't expect that. Nice work, thanks, @marmichalski !
> 
> As for 'static_cast' over 'c-style' cast, I haven't decided yet what I prefer more, usually I'm too lazy to write ***_cast<> etc but in general, I don't mind.

Hey, no problem. I have updated the visual studio project for box2d, the `src` dir is needed in the additional include paths because there is, I believe, not correctly included file in one of the source files. I will open up a PR in Box2D and see what they think - if it will be accepted, the additional include path could be removed, if not, will have to stay with us :P

I am not updating the casts, because I see no reason to. I can do that, if that's what you prefer, @codenamecpp, but I see you don't mind too :)

2021-11-26 22:24 UTC, merged